### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by FReina** [scstein/TrackNTrace#1]
Hello!
Thank you for the very useful work, I have been using it for my movies with a non-fluorescence based technique, and it works wonderfully.
I want to suggest that you could introduce, alongside the maximum step size that you already have, a minimum step size as well: my samples have a tendency of having spurious, static features which show up as tracks all the same, and that of course increases the amount of data to save and the computation time. 

Keep up the good work!

**Comment by thielec** [comment]
Is this still relevant for you? I will close this issue for now. If you still need this please open a new issue or write me a mail (christoph.thiele (at) phys.uni-goettingen.de).
